apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: yasserh/udagram-api-feed:latest
        name: backend-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: envconfigmap
        volumeMounts:
        - name: aws-volume
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-volume
          secret:
            secretName: aws-secret2